apiVersion: v2
description: cron job
name: app-cronjob
version: 0.2.3
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.6.0
    tags:
      - bitnami-common

  - name: someblackmagic-common
    repository: https://someblackmagic.github.io/helm-charts
    version: 0.x.x
    tags:
      - someblackmagic-common

maintainers:
  - name: Andrii Cherny
    url: https://github.com/wirwolf
