{{ if  $.Values.extraConfigMaps.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-extra-config-map" $.Release.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
{{- range $index, $content := $.Values.extraConfigMaps.data }}
  {{ $index }}: |-
{{ $content | indent 4 }}
{{- end }}
{{- end }}