{{- if and $.Values.metrics.enabled $.Values.metrics.serviceMonitor.enabled ( $.Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ $.Release.Name }}-pod-monitor
  namespace: {{ $.Values.metrics.serviceMonitor.namespace | default $.Release.Namespace }}
  labels:
    {{- if $.Values.metrics.serviceMonitor.labels }}
    {{- toYaml $.Values.metrics.serviceMonitor.labels | nindent 4}}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/chart-name: {{ $.Chart.Name }}
      app.kubernetes.io/release-name: {{ $.Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  podMetricsEndpoints:
    - port: monitoring
      scrapeTimeout: {{ $.Values.metrics.serviceMonitor.scrapeTimeout }}
      interval: {{ $.Values.metrics.serviceMonitor.scrapeInterval }}

{{- end }}
