apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  selector:
    app.kubernetes.io/chart-name: {{ $.Chart.Name }}
    app.kubernetes.io/release-name: {{ $.Release.Name }}
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: fpm

    - port: 9253
      targetPort: 9253
      protocol: TCP
      name: monitoring
  sessionAffinity: ClientIP
  sessionAffinityConfig:
      clientIP:
          timeoutSeconds: 30
