apiVersion: v2
description: swoole chart
name: app-swoole
version: 0.1.6
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.30.0
    tags:
      - bitnami-common

  - name: someblackmagic-common
    repository: https://someblackmagic.github.io/helm-charts
    version: 0.x.x
    tags:
      - someblackmagic-common

maintainers:
  - name: Andrii Cherny
    url: https://github.com/wirwolf
