metadata:
  deployedBy: null-value
  pipelineUrl: null-value

pvc:
  enabled: false
  name: ~
  size: 1Gi
  accessMode: ReadWriteMany
  storageClassName: ~
  volumePermissions:
    enabled: false
    #jobId: ~
    jobIdAutoGenerate: false
    runAsUser: 0
    fsGroup: 0

externalSecret:
  enabled: false
  refreshInterval: 30s
  secretStoreRef:
    name: ~
    kind: ClusterSecretStore
  targetSecretName: ~
  dataFrom: []
  data: []

businessLogicVars: {}
