{{ if and $.Values.pvc.enabled $.Values.pvc.volumePermissions.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}
  labels:
    helm.sh/chart-name: {{ $.Chart.Name }}
    helm.sh/chart-version: {{ $.Chart.Version }}
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  annotations:
    metadata/deployed-by: {{ $.Values.metadata.deployedBy | quote }}
    metadata/pipeline-url: {{ $.Values.metadata.pipelineUrl | quote }}
spec:
  backoffLimit: 1
  parallelism: 1
  ttlSecondsAfterFinished: 7200
  completions: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $.Release.Name }} # duplicate release name only for work helm-assistant
        app.kubernetes.io/chart-name: {{ $.Chart.Name }}
        app.kubernetes.io/release-name: {{ $.Release.Name }}
        app.metadata.io/version: {{ $.Chart.AppVersion | default "nill" | trunc 63 }}
    spec:
      volumes:
        - name: pvc-data
          persistentVolumeClaim:
            claimName: {{ $.Release.Name }}-{{ $.Values.pvc.name }}
      restartPolicy: OnFailure
      containers:
        - name: {{ $.Release.Name }}-job
          image: alpine:3
          command:
            - chown
            - -Rv
            - {{ $.Values.pvc.volumePermissions.runAsUser }}:{{ $.Values.pvc.volumePermissions.fsGroup }}
            - /mnt
          volumeMounts:
            - name: pvc-data
              mountPath: /mnt
{{ end }}
