apiVersion: batch/v1
kind: Job
metadata:
  {{ if $.Values.job.id }}
  name: {{ $.Release.Name }}-{{ $.Values.job.id }}
  {{ else if $.Values.job.idAutoGenerate }}
  name: {{ $.Release.Name }}-{{ lower (randAlphaNum 5) }}
  {{ else }}
  name: {{ $.Release.Name }}
  {{ end }}
  labels:
    helm.sh/chart-name: {{ $.Chart.Name }}
    helm.sh/chart-version: {{ $.Chart.Version }}
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  annotations:
    metadata/deployed-by: {{ $.Values.metadata.deployedBy | quote }}
    metadata/pipeline-url: {{ $.Values.metadata.pipelineUrl | quote }}
spec:
  backoffLimit: {{ $.Values.job.backoffLimit }}
  parallelism: {{ $.Values.job.parallelism }}
  ttlSecondsAfterFinished: {{ $.Values.job.ttlSecondsAfterFinished }}
  completions: {{ $.Values.job.completions }}
  activeDeadlineSeconds: {{ $.Values.job.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $.Release.Name }} # duplicate release name only for work helm-assistant
        app.kubernetes.io/chart-name: {{ $.Chart.Name }}
        app.kubernetes.io/release-name: {{ $.Release.Name }}
        app.metadata.io/version: {{ $.Chart.AppVersion | default "nill" }}
        {{- if $.Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" $.Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
      annotations:
        imageId: {{ $.Values.image.id | quote }}
        {{- range $item := $.Values.extraEnvVarsSecrets }}
        checksum/externalSecret_{{ $item.name }}: {{ $item.checksum | quote  }}
        {{- end }}
        {{- if $.Values.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" $.Values.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if $.Values.image.pullSecrets }}
      imagePullSecrets: {{ toYaml $.Values.image.pullSecrets | nindent 10 }}
      {{- end }}
      {{- if $.Values.podSecurityContext.enabled }}
      securityContext: {{- omit $.Values.podSecurityContext "enabled" | toYaml | nindent 12 }}
      {{- end }}

      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      restartPolicy: {{ $.Values.restartPolicy }}
      initContainers:
        {{- range $job := $.Values.initApplication }}
        - name: {{ $job.name }}
          {{- if ($job.customImageRepository) }}
          image: "{{ $.Values.image.registry }}/{{ $job.customImageRepository }}:{{ $.Values.image.tag }}"
          {{- else }}
          image: "{{ $.Values.image.registry }}/{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          {{- end }}

          imagePullPolicy: {{ $.Values.image.pullPolicy }}

          command: {{- include "common.cmd" (dict "value" $job.command "context" $) | nindent 12 }}
          args: {{- include "common.cmd" (dict "value" $job.args "context" $) | nindent 12 }}

          envFrom: {{- include "common.containerEnvVarsSecrets" (dict "value" $.Values.extraEnvVarsSecrets "context" $) | nindent 12 }}
          env: {{- include "common.containerEnvVars" (dict "value" $.Values.extraEnvVars "context" $) | nindent 12 }}

          {{- if $job.resources }}
          resources: {{ toYaml $job.resources | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if $.Values.initContainers }}
        {{- include "common.tplvalues.render" ( dict "value" $.Values.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ $.Values.job.name }}
          image: "{{ $.Values.image.registry }}/{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}

          {{- if $.Values.diagnosticMode.enabled }}
          command: {{- include "common.cmd" (dict "value" $.Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if $.Values.job.command }}
          command: {{- include "common.cmd" (dict "value" $.Values.job.command "context" $) | nindent 12 }}
          {{- end }}

          {{- if $.Values.diagnosticMode.enabled }}
          args: {{- include "common.cmd" (dict "value" $.Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if $.Values.job.arguments }}
          args: {{- include "common.cmd" (dict "value" $.Values.job.arguments "context" $) | nindent 12 }}
          {{- end }}

          envFrom: {{- include "common.containerEnvVarsSecrets" (dict "value" $.Values.extraEnvVarsSecrets "context" $) | nindent 12 }}
          env: {{- include "common.containerEnvVars" (dict "value" $.Values.extraEnvVars "context" $) | nindent 12 }}

          {{- if $.Values.resources.enabled }}
          resources: {{- omit $.Values.resources "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if $.Values.containerSecurityContext.enabled }}
          securityContext: {{- omit $.Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}


          lifecycle:
            preStop:
              exec:
                command: {{- include "common.cmd" (dict "value" $.Values.lifecycle.preStop "context" $) | nindent 18 }}

          volumeMounts:
            {{- if $.Values.extraVolumeMounts }}
            {{- include "common.tplvalues.render" ( dict "value" $.Values.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}

        {{- if $.Values.sidecars }}
        {{- include "common.tplvalues.render" (dict "value" $.Values.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        {{- if $.Values.extraVolumes }}
        {{- include "common.tplvalues.render" ( dict "value" $.Values.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
