{{- if $.Values.extraVhostConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-extra-vhost-config
data:
  extraVHostConfig.conf: |-
    {{- include "common.tplvalues.render" ( dict "value" $.Values.extraVhostConfig.content "context" $ ) | nindent 4 }}
---
{{- end }}

{{- if $.Values.extraConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-extra-config
data:
  extraConfig.conf: |-
    {{- include "common.tplvalues.render" ( dict "value" $.Values.extraConfig.content "context" $ ) | nindent 4 }}
---
{{- end }}

{{- if $.Values.externalUpstream.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-external-upstream
data:
  fpm-upstream.conf: |-
    upstream upstream-app {
        server {{ $.Values.externalUpstream.serviceName }}:{{ $.Values.externalUpstream.servicePort }} max_fails={{ $.Values.externalUpstream.maxFails }} fail_timeout={{ $.Values.externalUpstream.failTimeout }};
    }

---
{{- end }}
{{- if $.Values.extraFilterIp.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-extra-filter-ip
data:
  extraFilterIp.conf: |-
    error_page 403 /403.html;

    {{- range $item := $.Values.extraFilterIp.allow }}
    allow {{ $item }};
    {{- end }}
    {{- range $item := $.Values.extraFilterIp.deny }}
    deny {{ $item }};
    {{- end }}
    {{ $.Values.extraFilterIp.defaultPermission }} all;

    location /403.html {
      return 403 '{{ $.Values.extraFilterIp.forbiddenText }}';
      allow all;
    }

---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-monitoring-conf
data:
  monitoring.conf: |-
    server {
      listen 8888 default_server;
      server_name _;

      access_log off;

      location /stub_status {
      stub_status;
      }
    }

