apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if $.Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  selector:
    app.kubernetes.io/chart-name: {{ $.Chart.Name }}
    app.kubernetes.io/release-name: {{ $.Release.Name }}
  type: ClusterIP
  ports:
    - name: http
      port: {{ $.Values.service.ports.http }}
      targetPort: {{ $.Values.containerPorts.http }}
      protocol: TCP

    {{- if $.Values.metrics.enabled }}
    - port: 9113
      targetPort: 9113
      protocol: TCP
      name: monitoring
    {{- end }}

    {{- if $.Values.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" $.Values.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
      clientIP:
          timeoutSeconds: 30
