{{- if and (eq $.Values.externalSecret.enabled true) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: {{ $.Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.externalSecret.secretStoreRef.name }}
    kind: {{ $.Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ $.Release.Name }}-external-secret

  dataFrom:
    {{- if $.Values.externalSecret.dataFrom }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.externalSecret.dataFrom "context" $) | nindent 4 }}
    {{- end }}
  data:
    - remoteRef:
        key:
      secretKey:

{{- end }}
